'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { 
  Landmark, 
  CheckCircle2, 
  Clock, 
  FileText, 
  ShieldCheck, 
  ArrowLeft, 
  KeyRound,
  AlertCircle,
  Eye,
  Check,
  X
} from 'lucide-react'
import { MazhiShetiLogo } from '@/components/ui/MazhiShetiLogo'
import { UserButton, useUser } from '@clerk/nextjs'
import { Download, Sparkles } from 'lucide-react'

export default function BankDashboardPage() {
  const { user } = useUser()
  const [applications, setApplications] = useState([
    {
      id: 'app-01',
      applicationNo: 'MSCB-KCC-2026-8891',
      farmerName: 'Anandarao Patil',
      village: 'Malegaon, Baramati',
      totalLandAcres: 14.5,
      scheme: 'Kisan Credit Card (KCC) Crop Working Capital',
      amount: 350000.0,
      soilHealthScore: 82.0,
      soilGrade: 'Grade A (Fertile)',
      crops: 'Sugarcane, Soybean, Pomegranate',
      status: 'APPROVED',
      consentScopes: ['farm_ownership', 'soil_health', 'crop_history'],
      consentVerified: true,
      appliedDate: '12 Jan 2026',
      requestedDocs: [] as string[],
    },
    {
      id: 'app-02',
      applicationNo: 'MSCB-AIF-2026-1044',
      farmerName: 'Balasaheb Jagtap',
      village: 'Morgaon, Baramati',
      totalLandAcres: 8.0,
      scheme: 'Agri Infrastructure Fund — Solar Irrigation Pump',
      amount: 180000.0,
      soilHealthScore: 74.0,
      soilGrade: 'Grade B (Adequate)',
      crops: 'Onion, Wheat, Bajra',
      status: 'UNDER_REVIEW',
      consentScopes: ['farm_ownership', 'soil_health'],
      consentVerified: true,
      appliedDate: 'Yesterday',
      requestedDocs: [] as string[],
    },
  ])

  const [selectedFarmer, setSelectedFarmer] = useState<any>(applications[0])
  const [toastMessage, setToastMessage] = useState<string | null>(null)
  const [docModalApp, setDocModalApp] = useState<any>(null)
  const [selectedDocs, setSelectedDocs] = useState<string[]>([
    '7/12 Land Title Extract (Digitally Signed)',
    'Soil Health Card & Soil Assay Report'
  ])

  const documentOptions = [
    '7/12 Land Title Extract (Digitally Signed)',
    '8-A Land Holding Certificate',
    'Soil Health Card & Soil Assay Report',
    'Current Crop Sowing Photo & Geo-Tag',
    'Past 6 Months Bank Statement / Passbook',
    'No-Objection Certificate from PACS'
  ]

  const toggleDoc = (doc: string) => {
    if (selectedDocs.includes(doc)) {
      setSelectedDocs(selectedDocs.filter(d => d !== doc))
    } else {
      setSelectedDocs([...selectedDocs, doc])
    }
  }

  const handleUpdateStatus = (appId: string, newStatus: string) => {
    setApplications(applications.map((a) => (a.id === appId ? { ...a, status: newStatus } : a)))
    if (selectedFarmer?.id === appId) {
      setSelectedFarmer({ ...selectedFarmer, status: newStatus })
    }
    setToastMessage(`Application ${appId} status updated to: ${newStatus}. Immutable audit entry logged.`)
    setTimeout(() => setToastMessage(null), 4000)
  }

  const handleDispatchDocRequest = (e: React.FormEvent) => {
    e.preventDefault()
    if (!docModalApp) return

    setApplications(
      applications.map(a => 
        a.id === docModalApp.id 
          ? { ...a, status: 'DOCUMENTS_REQUIRED', requestedDocs: selectedDocs } 
          : a
      )
    )

    if (selectedFarmer?.id === docModalApp.id) {
      setSelectedFarmer({ ...selectedFarmer, status: 'DOCUMENTS_REQUIRED', requestedDocs: selectedDocs })
    }

    setToastMessage(`Official notice dispatched to ${docModalApp.farmerName} for: ${selectedDocs.length} documents.`)
    setDocModalApp(null)
    setTimeout(() => setToastMessage(null), 5000)
  }

  const handleExportAppraisal = () => {
    if (!selectedFarmer) return
    const content = `
MAZHI SHETI — CREDIT APPRAISAL MEMORANDUM
Application No: ${selectedFarmer.applicationNo}
Farmer: ${selectedFarmer.farmerName} (${selectedFarmer.village})
Land Holdings: ${selectedFarmer.totalLandAcres} Acres
Facility: ${selectedFarmer.scheme}
Amount: INR ${selectedFarmer.amount.toLocaleString()}
Soil Health Index: ${selectedFarmer.soilHealthScore}/100 (${selectedFarmer.soilGrade})
Crops: ${selectedFarmer.crops}
Consent Scopes: ${selectedFarmer.consentScopes.join(', ')}
Status: ${selectedFarmer.status}
Generated By: MSCB Agri Underwriting Desk
    `.trim()

    // Create a client download or copy
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `Appraisal_${selectedFarmer.applicationNo}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

    setToastMessage(`Credit Appraisal Note for ${selectedFarmer.farmerName} downloaded successfully.`)
    setTimeout(() => setToastMessage(null), 4000)
  }

  return (
    <div className="min-h-screen bg-[#070B16] text-slate-100 flex flex-col selection:bg-blue-500/25 selection:text-blue-400 relative">
      
      {/* Toast Notification Banner */}
      {toastMessage && (
        <div className="fixed top-20 right-6 z-50 p-4 rounded-2xl bg-[#0B1A3A] border border-blue-500/40 text-blue-200 shadow-2xl flex items-center gap-3 text-xs font-mono animate-in slide-in-from-top duration-300">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{toastMessage}</span>
          <button onClick={() => setToastMessage(null)} className="text-slate-400 hover:text-white ml-2">
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* Top Bank Header */}
      <header className="sticky top-0 z-40 bg-[#0B152E]/90 backdrop-blur-xl border-b border-white/10 px-6 sm:px-10 py-3.5 flex items-center justify-between shadow-xl">
        <div className="flex items-center gap-6">
          <Link href="/bank/dashboard" className="flex items-center gap-3">
            <MazhiShetiLogo size={32} showText={true} showBadge={true} roleLabel="Bank" subtitle="SOVEREIGN AGRI PLATFORM" />
          </Link>

          <div className="hidden lg:flex items-center gap-2 px-3 py-1 rounded-xl bg-blue-500/10 border border-blue-500/20 text-xs font-mono">
            <Landmark className="w-3.5 h-3.5 text-blue-400" />
            <span className="text-blue-200">Officer:</span>
            <span className="font-bold text-white">
              {user?.fullName || 'Ramesh Kulkarni'} (MSCB Agri Credit)
            </span>
            <span className="px-2 py-0.2 rounded bg-emerald-500/20 text-emerald-400 font-bold ml-1 text-[10px]">
              VERIFIED
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2.5 sm:gap-3">
          <Link
            href="/"
            className="px-3 py-1.5 rounded-xl bg-white/[0.05] hover:bg-white/[0.1] border border-white/10 text-xs font-sans font-semibold text-blue-100"
          >
            ← Home
          </Link>

          {/* Verified Role Indicator */}
          <div className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-blue-500/10 border border-blue-500/30 text-xs font-mono text-blue-300">
            <span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
            <span className="font-bold">Bank Portal</span>
          </div>

          <UserButton 
            appearance={{
              elements: {
                userButtonAvatarBox: 'w-8 h-8 rounded-xl border border-blue-500/40 shadow-sm',
              }
            }}
          />
        </div>
      </header>

      {/* Main Bank Content */}
      <main className="flex-1 p-4 sm:p-8 max-w-7xl mx-auto w-full space-y-8">
        
        {/* KPI Strip */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 font-mono text-xs">
          <div className="p-5 rounded-2xl bg-[#0B152E]/90 border border-white/10 space-y-1">
            <span className="text-blue-200/60 block">Inbound Credit Applications</span>
            <span className="font-display font-black text-3xl text-white block">₹5,30,000</span>
            <span className="text-blue-300">2 Active Farmer Files</span>
          </div>

          <div className="p-5 rounded-2xl bg-[#0B152E]/90 border border-white/10 space-y-1">
            <span className="text-blue-200/60 block">Consent Verification State</span>
            <span className="font-display font-black text-3xl text-emerald-400 block">100%</span>
            <span className="text-emerald-300">Cryptographically Audited</span>
          </div>

          <div className="p-5 rounded-2xl bg-[#0B152E]/90 border border-white/10 space-y-1">
            <span className="text-blue-200/60 block">Approved Disbursements</span>
            <span className="font-display font-black text-3xl text-white block">
              ₹{applications.filter(a => a.status === 'APPROVED').reduce((acc, a) => acc + a.amount, 0).toLocaleString()}
            </span>
            <span className="text-emerald-400">
              {applications.filter(a => a.status === 'APPROVED').length} KCC Sanctioned
            </span>
          </div>

          <div className="p-5 rounded-2xl bg-[#0B152E]/90 border border-white/10 space-y-1">
            <span className="text-blue-200/60 block">Average Farm Health</span>
            <span className="font-display font-black text-3xl text-white block">78 / 100</span>
            <span className="text-blue-200">Low Default Probability</span>
          </div>
        </div>

        {/* Loan Queue & Consent-Gated Dossier Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Left 2 Cols: Loan Application Queue */}
          <div className="lg:col-span-2 space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="font-display font-bold text-lg text-white">Underwriting Application Queue</h2>
              <span className="text-xs font-mono text-blue-200/60">Least-Privilege Role: BANK_LOAN_OFFICER</span>
            </div>

            <div className="space-y-3">
              {applications.map((app) => (
                <div
                  key={app.id}
                  onClick={() => setSelectedFarmer(app)}
                  className={`p-5 rounded-2xl border cursor-pointer transition-all space-y-3 ${
                    selectedFarmer?.id === app.id
                      ? 'bg-[#0E1F42] border-blue-400 shadow-xl shadow-blue-950/40'
                      : 'bg-[#0B152E]/80 border-white/10 hover:border-white/20'
                  }`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                    <div>
                      <span className="text-xs font-mono text-orange-400 font-bold block">{app.applicationNo}</span>
                      <h3 className="font-sans font-bold text-base text-white">{app.farmerName}</h3>
                      <span className="text-xs text-blue-200/70 font-sans">{app.village} • {app.totalLandAcres} Acres</span>
                    </div>

                    <div className="text-right">
                      <span className="font-display font-black text-2xl text-white block">₹{app.amount.toLocaleString()}</span>
                      <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold ${
                        app.status === 'APPROVED' ? 'bg-emerald-500/20 text-emerald-400' : 
                        app.status === 'DOCUMENTS_REQUIRED' ? 'bg-amber-500/20 text-amber-400' :
                        'bg-orange-500/20 text-orange-400'
                      }`}>
                        {app.status}
                      </span>
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-white/[0.03] flex items-center justify-between text-xs font-mono">
                    <span className="text-blue-200">{app.scheme}</span>
                    <span className="text-emerald-400 font-bold flex items-center gap-1">
                      <ShieldCheck className="w-3.5 h-3.5" />
                      Consent Verified ✓
                    </span>
                  </div>

                  {app.requestedDocs && app.requestedDocs.length > 0 && (
                    <div className="p-2.5 rounded-lg bg-amber-500/10 border border-amber-500/20 text-[11px] font-mono text-amber-300">
                      <strong>Requested Docs:</strong> {app.requestedDocs.join(', ')}
                    </div>
                  )}

                  {/* Underwriter Action Buttons */}
                  <div className="pt-2 border-t border-white/10 flex items-center justify-end gap-2">
                    {app.status !== 'APPROVED' && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation()
                          handleUpdateStatus(app.id, 'APPROVED')
                        }}
                        className="px-3.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-sans font-bold uppercase transition-all flex items-center gap-1.5 shadow-md shadow-emerald-950/40"
                      >
                        <Check className="w-3.5 h-3.5" />
                        <span>Approve Loan</span>
                      </button>
                    )}
                    {app.status !== 'DOCUMENTS_REQUIRED' && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation()
                          setDocModalApp(app)
                        }}
                        className="px-3 py-1.5 rounded-lg bg-white/[0.06] hover:bg-white/[0.12] text-blue-200 text-xs font-sans font-bold transition-all border border-white/10"
                      >
                        Request Documents
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Right 1 Col: Consent-Verified Dossier */}
          <div className="space-y-4">
            <h2 className="font-display font-bold text-lg text-white">Consent-Verified Dossier</h2>

            {selectedFarmer ? (
              <div className="p-6 rounded-2xl bg-[#0B152E]/90 border border-blue-500/30 backdrop-blur-xl shadow-xl space-y-5">
                <div className="border-b border-white/10 pb-3 flex items-start justify-between">
                  <div>
                    <span className="text-xs font-mono text-emerald-400 font-bold flex items-center gap-1.5">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      Authorized Access: Token Active
                    </span>
                    <h3 className="font-display font-bold text-xl text-white mt-1">{selectedFarmer.farmerName}</h3>
                    <span className="text-xs font-mono text-blue-300/70">Holdings: {selectedFarmer.totalLandAcres} Acres Owned</span>
                  </div>

                  <button
                    onClick={handleExportAppraisal}
                    className="p-2 rounded-xl bg-blue-500/10 hover:bg-blue-500/20 text-blue-300 border border-blue-500/30 text-xs font-mono transition-all flex items-center gap-1"
                    title="Download Credit Appraisal Note"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span className="hidden sm:inline">Export</span>
                  </button>
                </div>

                {/* Verified Metrics */}
                <div className="space-y-3 text-xs font-mono">
                  <div className="p-3.5 rounded-xl bg-white/[0.03] space-y-1">
                    <span className="text-blue-200/60 block">Soil Health Index (Audited):</span>
                    <span className="font-black text-emerald-400 text-lg block">{selectedFarmer.soilHealthScore} / 100</span>
                    <span className="text-[10px] text-blue-200/70">{selectedFarmer.soilGrade}</span>
                  </div>

                  <div className="p-3.5 rounded-xl bg-white/[0.03] space-y-1">
                    <span className="text-blue-200/60 block">Verified Crop History:</span>
                    <span className="font-bold text-white block">{selectedFarmer.crops}</span>
                  </div>

                  <div className="p-3.5 rounded-xl bg-white/[0.03] space-y-1">
                    <span className="text-blue-200/60 block">Granted Consent Scopes:</span>
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {selectedFarmer.consentScopes.map((sc: string) => (
                        <span key={sc} className="px-2 py-0.5 rounded bg-blue-500/20 text-blue-300 text-[10px] font-bold">
                          ✓ {sc}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                <div className="pt-2 border-t border-white/10 text-[11px] font-mono text-blue-200/50">
                  Audit Entry: Read logged under MSCB Officer Session. Private AI & non-consented records strictly blocked.
                </div>
              </div>
            ) : (
              <div className="p-8 rounded-2xl bg-[#0B152E]/90 border border-white/10 text-center text-xs font-mono text-neutral-400">
                Select a farmer application to inspect authorized dossier.
              </div>
            )}
          </div>

        </div>

      </main>

      {/* Document Request Checklist Modal */}
      {docModalApp && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="max-w-lg w-full rounded-2xl bg-[#0C1938] border border-blue-500/40 p-6 shadow-2xl space-y-5 animate-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <div>
                <h3 className="font-display font-bold text-lg text-white">Request Verification Documents</h3>
                <span className="text-xs font-mono text-blue-300">
                  Application: {docModalApp.applicationNo} • {docModalApp.farmerName}
                </span>
              </div>
              <button
                onClick={() => setDocModalApp(null)}
                className="text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleDispatchDocRequest} className="space-y-4 text-xs font-mono">
              <div className="space-y-2">
                <label className="text-slate-300 font-bold block">Select Required Official Records:</label>
                <div className="space-y-2">
                  {documentOptions.map((doc) => {
                    const isSelected = selectedDocs.includes(doc)
                    return (
                      <div
                        key={doc}
                        onClick={() => toggleDoc(doc)}
                        className={`p-3 rounded-xl border cursor-pointer transition-all flex items-center justify-between ${
                          isSelected
                            ? 'bg-blue-500/20 border-blue-500/60 text-white font-bold'
                            : 'bg-white/[0.02] border-white/10 text-slate-400 hover:text-white'
                        }`}
                      >
                        <span>{doc}</span>
                        <span className={`w-4 h-4 rounded flex items-center justify-center text-[10px] font-bold ${
                          isSelected ? 'bg-blue-500 text-white' : 'border border-white/20'
                        }`}>
                          {isSelected ? '✓' : ''}
                        </span>
                      </div>
                    )
                  })}
                </div>
              </div>

              <div className="pt-3 border-t border-white/10 flex items-center justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setDocModalApp(null)}
                  className="px-4 py-2 rounded-xl bg-white/[0.05] hover:bg-white/[0.1] text-slate-300 text-xs font-sans"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={selectedDocs.length === 0}
                  className="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white font-sans font-bold text-xs uppercase tracking-wider transition-all shadow-lg shadow-blue-950/50 flex items-center gap-1.5"
                >
                  <span>Dispatch Official Notice ({selectedDocs.length})</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  )
}
